#pragma once

#include "Game/System/ArchiveHolder.h"
#include "Game/System/BinaryDataChunkHolder.h"
#include "Game/System/FileLoader.h"
#include "Game/System/GameEventFlagTable.h"
#include "Game/System/GameSystem.h"
#include "Game/System/GameSystemDataHolder.h"
#include "Game/System/GameSystemDimmingWatcher.h"
#include "Game/System/GameSystemFunction.h"
#include "Game/System/GameSystemObjHolder.h"
#include "Game/System/GameSequenceInGame.h"
#include "Game/System/GameSystemErrorWatcher.h"
#include "Game/System/HeapMemoryWatcher.h"
#include "Game/System/Language.h"
#include "Game/System/MainLoopFramework.h"
#include "Game/System/NerveExecutor.h"
#include "Game/System/PlayResultInStageHolder.h"
#include "Game/System/ResourceHolder.h"
#include "Game/System/ResourceHolderManager.h"
#include "Game/System/ResourceInfo.h"
#include "Game/System/ScenarioDataParser.h"
#include "Game/System/WPadHolder.h"

#include "Game/System/AllData/GalaxyStatusAccessor.h"
#include "Game/System/AllData/GameDataFunction.h"
#include "Game/System/AllData/GameDataHolder.h"
#include "Game/System/AllData/GameSequenceFunction.h"
#include "Game/System/AllData/SaveDataHandleSequence.h"
#include "Game/System/AllData/SaveDataHandler.h"

#include "Game/System/GameData/GameDataGalaxyStorage.h"
#include "Game/System/GameData/UserFile.h"
